
"""
Django settings for LibraryProject project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
...
"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.
...
"""

from pathlib import Path
import os
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    ...
]
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',  # ✅ Add this line
]

"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o=y2&0q^zl7q)01+n%&n3d%@58+hnux+=$14uwuij8ri_55t2j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',  # ← Add this line
]
